# Pandas处理时间数据  

欢迎来到时间序列数据处理训练营关卡1：Pandas处理时间数据。在本节中，我们将深入探讨如何使用Pandas库来处理和操作时间序列数据。  
Pandas是一个强大的数据分析工具，特别适用于处理时间相关的数据。通过本关卡的学习，你将掌握如何创建时间戳、日期时间索引、时间段、时间差等，并了解如何进行时区处理和数据加载。这些技能对于时间序列分析、数据预处理和特征工程至关重要。

# 一、Pandas在时间处理方面的应用  
## Pandas功能  
在时间处理时，Pandas能够生成固定频率的日期和时间跨度序列；将时间序列调整或转换为特定的频率；根据非标准的时间间隔计算"相对"日期（例如，年底前的5个工作日），或者向前或向后滚动日期。

## Pandas时间相关的数据类型  

![Image Name](https://cdn.kesci.com/upload/seby2jzyux.png?imageView2/0/w/960/h/960)

In [2]:
import pandas as pd
import numpy as np

# 二、Timestamp  （时间戳）

In [3]:
#创建表示特定日期的时间戳
pd.Timestamp('2016-07-10')

Timestamp('2016-07-10 00:00:00')

In [4]:
#增加细节 使时间戳更细致
pd.Timestamp('2016-07-10 10')

Timestamp('2016-07-10 10:00:00')

In [5]:
#再加细节
pd.Timestamp('2016-07-10 10:15')

Timestamp('2016-07-10 10:15:00')

思考： 一共可以增加多少细节？

In [6]:
pd.Timestamp("2012-03-10 10:13:55")

Timestamp('2012-03-10 10:13:55')

In [10]:
# 时间戳有哪些属性？
# 提示： http://pandas.pydata.org/pandas-docs/stable/timeseries.html#time-date-components
t = pd.Timestamp('2026-03-30 14:48:53')

## 时间/日期组件  
可以从时间戳（Timestamp）或时间戳集合（如DateTimeIndex）中访问的几个时间/日期属性。  

![Image Name](https://cdn.kesci.com/upload/sebz5z7psd.png?imageView2/0/w/960/h/960)

In [13]:
print("---周---")
print(t.weekday_name)
print('---秒---')
print(t.second)
print('---一年中的第几天---')
print(t.dayofyear)

---周---
Monday
---秒---
53
---一年中的第几天---
89

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: `weekday_name` is deprecated and will be removed in a future version. Use `day_name` instead

<h1>二、DatetimeIndex（日期时间编码器）</h1><p>日期时间索引的主要用途之一是作为Pandas对象的索引<br>日期时间索引类包含许多与时间序列相关的优化：<br>· 在底层预先计算并缓存了各种偏移量的大范围日期，以便快速生成后续的日期范围（只需获取一个切片）。<br>· 可以使用 shift 和 tshift 方法来对数据进行快速的移动或偏移操作，<strong>偏移（Offset）</strong> 就是<strong>时间的「步长」或「单位」</strong>，用来表示「时间移动的幅度」和「时间序列的频率」。<br>· 对于具有相同频率的重叠的 DatetimeIndex 对象进行合并是非常快速的（这对于快速的数据对齐非常重要）。<br>· 可以通过年份、月份等属性快速访问日期字段。<br>· 包含正则化函数（snap,asof etc.）。</p><p>偏移是 Pandas 时间序列的<strong>核心规则</strong>，所有时间相关操作都依赖它：</p><ul><li><p>生成时间序列（<code>date_range</code>）</p></li><li><p>时间移动 / 偏移（<code>shift</code>/<code>tshift</code>）</p></li><li><p>数据重采样（<code>resample</code>）</p></li><li><p>时间对齐（<code>asof</code></p></li></ul><p></p>

<h2>偏移别名</h2><p>在 Pandas 中一些常见的时间序列频率被赋予了一些字符串别名，这些别名被称为偏移别名（在 v0.8.0 之前被称为时间规则）。</p><p></p><table style="min-width: 100px;"><colgroup><col style="min-width: 25px;"><col style="min-width: 25px;"><col style="min-width: 25px;"><col style="min-width: 25px;"></colgroup><tbody><tr><th colspan="1" rowspan="1"><p>别名</p></th><th colspan="1" rowspan="1"><p>全称（偏移类型）</p></th><th colspan="1" rowspan="1"><p>含义</p></th><th colspan="1" rowspan="1"><p>金融场景用法</p></th></tr><tr><td colspan="1" rowspan="1"><p><code>B</code></p></td><td colspan="1" rowspan="1"><p>BusinessDay</p></td><td colspan="1" rowspan="1"><p>工作日（周一到周五，排除周末）</p></td><td colspan="1" rowspan="1"><p>生成股票交易日序列、按工作日重采样</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>D</code></p></td><td colspan="1" rowspan="1"><p>Day</p></td><td colspan="1" rowspan="1"><p>自然日（周一到周日，包含周末）</p></td><td colspan="1" rowspan="1"><p>生成自然日时间序列、计算自然日收益率</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>W</code></p></td><td colspan="1" rowspan="1"><p>Week</p></td><td colspan="1" rowspan="1"><p>周（默认周日为周期结束）</p></td><td colspan="1" rowspan="1"><p>计算周度收盘价、周度均线</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>M</code></p></td><td colspan="1" rowspan="1"><p>MonthEnd</p></td><td colspan="1" rowspan="1"><p>月末（每月最后一个自然日）</p></td><td colspan="1" rowspan="1"><p>计算月度收益率、筛选月度最后一个交易日</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>Q</code></p></td><td colspan="1" rowspan="1"><p>QuarterEnd</p></td><td colspan="1" rowspan="1"><p>季末（每季度最后一个自然日）</p></td><td colspan="1" rowspan="1"><p>计算季度收益率、财务报表周期对齐</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>A</code>/<code>Y</code></p></td><td colspan="1" rowspan="1"><p>YearEnd</p></td><td colspan="1" rowspan="1"><p>年末（每年最后一个自然日）</p></td><td colspan="1" rowspan="1"><p>计算年度收益率、年度业绩统计</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>H</code></p></td><td colspan="1" rowspan="1"><p>Hour</p></td><td colspan="1" rowspan="1"><p>小时</p></td><td colspan="1" rowspan="1"><p>处理分钟级 / 小时级高频交易数据</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>T</code>/<code>min</code></p></td><td colspan="1" rowspan="1"><p>Minute</p></td><td colspan="1" rowspan="1"><p>分钟</p></td><td colspan="1" rowspan="1"><p>处理股票 Level-2 行情、高频交易</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>S</code></p></td><td colspan="1" rowspan="1"><p>Second</p></td><td colspan="1" rowspan="1"><p>秒</p></td><td colspan="1" rowspan="1"><p>处理逐笔成交数据</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>U</code></p></td><td colspan="1" rowspan="1"><p>Microsecond</p></td><td colspan="1" rowspan="1"><p>微秒</p></td><td colspan="1" rowspan="1"><p>处理超高频量化交易数据</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>N</code></p></td><td colspan="1" rowspan="1"><p>Nanosecond</p></td><td colspan="1" rowspan="1"><p>纳秒</p></td><td colspan="1" rowspan="1"><p>处理毫秒级行情数据</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>BM</code></p></td><td colspan="1" rowspan="1"><p>BusinessMonthEnd</p></td><td colspan="1" rowspan="1"><p>工作日月末（每月最后一个交易日）</p></td><td colspan="1" rowspan="1"><p>金融场景<strong>最常用</strong>，筛选月度最后一个交易日</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>BQ</code></p></td><td colspan="1" rowspan="1"><p>BusinessQuarterEnd</p></td><td colspan="1" rowspan="1"><p>工作日季末</p></td><td colspan="1" rowspan="1"><p>筛选季度最后一个交易日</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>BA</code>/<code>BY</code></p></td><td colspan="1" rowspan="1"><p>BusinessYearEnd</p></td><td colspan="1" rowspan="1"><p>工作日年末</p></td><td colspan="1" rowspan="1"><p>筛选年度最后一个交易日</p></td></tr></tbody></table><p></p>

In [7]:
#创建日期时间索引 rng，起始日期为'2016年7月1日'，并且频率为每日一次（'D'），共包含10个日期时间点
rng = pd.date_range('2016 Jul 1',periods = 10, freq = 'D')
rng

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10'],
              dtype='datetime64[ns]', freq='D')

思考：  
1.  以下哪种格式与其他的格式含义不同？  
  '2016 Jul 1'    '7/1/2016'     '1/7/2016'     'July 1, 2016'     '2016-07-01'     '2016/07/01'  
3.  7/1/2016 是一月还是七月？  
4.  date_range中保存的单个对象的类别是什么？

## 日期偏移对象  
在Pandas中，通过传递例如'M'、'W'和'BM'等频率字符串到freq关键字参数，我们创建了不同频率的DatetimeIndex对象。这些频率字符串在底层被转换为 pandas 的 DateOffset 实例，它代表了一种常规的频率增量。特定的偏移逻辑，如"月"、"工作日"或"一小时"，则在它的各种子类中表示。  

![Image Name](https://cdn.kesci.com/upload/sebzbmm1ri.png?imageView2/0/w/960/h/960)

In [8]:
#DateOffset 示例，以下所示了夏令时的情况：
# 生成一个指定的时间，芬兰赫尔辛基时间执行夏令时
ts = pd.Timestamp('2016-10-30 00:00:00', tz='Europe/Helsinki')
ts
# Timestamp('2016-10-30 00:00:00+0300', tz='Europe/Helsinki')
 
# 按日历时间
ts + pd.DateOffset(days=1)
# Timestamp('2016-10-31 00:00:00+0200', tz='Europe/Helsinki')

Timestamp('2016-10-31 00:00:00+0200', tz='Europe/Helsinki')

## 锚定后缀  
在 Pandas 中，除了常见的时间序列频率别名（如'D'表示每日频率、'W'表示每周频率等），还可以在某些频率后面添加一个特定的后缀，以指定时间序列中数据点的锚定点或起始点。  

![Image Name](https://cdn.kesci.com/upload/sebzkw859e.png?imageView2/0/w/960/h/960)

In [9]:
#当n不为0时，如果给定日期不在锚点上，则它会捕捉到下一个（上一个）锚点，并向前或向后移动 |n|-1 步。
pd.Timestamp('2014-01-02') + pd.offsets.MonthBegin(n=1)
# Timestamp('2014-02-01 00:00:00')

Timestamp('2014-02-01 00:00:00')

In [10]:
#如果给定的日期在锚点上，则将其| n |移动。 指向前进或后退：
pd.Timestamp('2014-01-01') + pd.offsets.MonthBegin(n=1)
# Timestamp('2014-02-01 00:00:00')

Timestamp('2014-02-01 00:00:00')

In [11]:
#对于n = 0的情况，如果在锚点上，则日期不会移动，否则它将前滚到下一个锚点。
pd.Timestamp('2014-01-02') + pd.offsets.MonthBegin(n=0)
# Timestamp('2014-02-01 00:00:00')

Timestamp('2014-02-01 00:00:00')

## 节假日和节假日日历  
在 Pandas 中，可以通过创建节假日日历类来定义一组特定的节假日规则。AbstractHolidayCalendar 类提供了必要的方法来返回节假日列表，而具体的规则则需要在特定的节假日日历类中定义。此外，start_date 和 end_date 类属性用于确定生成节假日的日期范围。应该在 AbstractHolidayCalendar 类上进行覆盖，以使这个范围适用于所有日历子类。

在 Pandas 中，已经预先定义了一些节假日日历，其中最常用的是 usFederalHolidayCalendar。它主要作为开发其他日历的示例。  
对于那些在固定日期发生的节假日（例如美国的纪念日或7月4日），如果节假日恰逢周末或其他非工作日，则会根据一个观察规则来确定其观察日期。已定义的观察规则如下：  

![Image Name](https://cdn.kesci.com/upload/sebzq6emcz.png?imageView2/0/w/960/h/960)

In [14]:
#生成节假日
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday
class ChinaHolidaysCalendar(AbstractHolidayCalendar):
    rules = [
        Holiday('元旦', month=1, day=1),
        Holiday('元旦', month=1, day=2),
        Holiday('元旦', month=1, day=3),
        Holiday('春节', month=1, day=21),
        Holiday('春节', month=1, day=22),
        # 同样的方法添加其他节假日
    ]

start_date = '2023-01-01'
end_date = '2023-12-31'

china_holidays_calendar = ChinaHolidaysCalendar()
holidays = china_holidays_calendar.holidays(start_date, end_date)
print(holidays)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-21',
               '2023-01-22'],
              dtype='datetime64[ns]', freq=None)

# 三、period（周期）

In [15]:
#创建表示特定月份的时间段
pd.Period('2016-01')

Period('2016-01', 'M')

思考：  
上面的额外信息是什么？它是如何设置的？

In [16]:
#创建表示特定日期的时间段
pd.Period('2016-01-01')

Period('2016-01-01', 'D')

In [17]:
#增加细节 使时间段更细致
pd.Period('2016-01-01 10')

Period('2016-01-01 10:00', 'H')

In [18]:
#增加细节 使时间段更细致
pd.Period('2016-01-01 10:10')

Period('2016-01-01 10:10', 'T')

In [19]:
#再加细节
pd.Period('2016-01-01 10:10:10')

Period('2016-01-01 10:10:10', 'S')

思考：  
1.  你能得到的最详细的时间段是什么？  
2.  如何制作多个时间段？  提示：寻找与上面 pd.date_range（） 的类比

## timedelta

In [20]:
#创建表示时间差的 Timedelta 对象，表示一天的时间跨度
pd.Timedelta('1 day')

Timedelta('1 days 00:00:00')

In [21]:
#将时间段和时间差相加，得到新的时间段
pd.Period('2016-01-01 10:10') + pd.Timedelta('1 day')

Period('2016-01-02 10:10', 'T')

In [22]:
#将时间戳和时间差相加，得到新的时间戳
pd.Timestamp('2016-01-01 10:10') + pd.Timedelta('1 day')

Timestamp('2016-01-02 10:10:00')

In [21]:
pd.Timestamp('2016-01-01 10:10') + pd.Timedelta('15 ns')

Timestamp('2016-01-01 10:10:00.000000015')

# 四、PeriodIndex（周期索引）

In [25]:
#花式频率设置
#在指定的时间范围内生成一系列时间段
#只要工作日
pd.period_range('2016-01-01 10:10',freq = 'M',periods = 10)

PeriodIndex(['2016-01', '2016-02', '2016-03', '2016-04', '2016-05', '2016-06',
             '2016-07', '2016-08', '2016-09', '2016-10'],
            dtype='period[M]', freq='M')

In [23]:
# 可以组合频率。如果想每天提前 25 小时怎么办？有哪两种方法可以做到这一点？
p1 = pd.period_range('2016-01-01 10:10',freq = '25H',periods = 10)

In [24]:
p2 = pd.period_range('2016-01-01 10:10',freq = '1D1H',periods = 10)

In [25]:
p2

PeriodIndex(['2016-01-01 10:00', '2016-01-02 11:00', '2016-01-03 12:00',
             '2016-01-04 13:00', '2016-01-05 14:00', '2016-01-06 15:00',
             '2016-01-07 16:00', '2016-01-08 17:00', '2016-01-09 18:00',
             '2016-01-10 19:00'],
            dtype='period[25H]', freq='25H')

思考：你还能制作哪些其他组合？

In [26]:
# 使用 TIME 对象编制索引
# 创建包含 10 个日期的时间索引，然后创建以这些日期为索引、以对应位置的整数为值的序列
rng = pd.date_range('2016 Jul 1',periods = 10,freq = 'D')
rng
pd.Series(range(len(rng)),index = rng)

2016-07-01    0
2016-07-02    1
2016-07-03    2
2016-07-04    3
2016-07-05    4
2016-07-06    5
2016-07-07    6
2016-07-08    7
2016-07-09    8
2016-07-10    9
Freq: D, dtype: int64

In [27]:
# 也可以使用时间段索引
# 将索引视为一个时间跨度，而不是单个时间点
periods = [pd.Period('2016-01'),pd.Period('2016-02'),pd.Period('2016-03')]
ts = pd.Series(np.random.randn(len(periods)),index = periods)
ts

2016-01    0.066424
2016-02   -1.530238
2016-03    0.329244
Freq: M, dtype: float64

In [28]:
# ts的索引类型
type(ts.index)

pandas.core.indexes.period.PeriodIndex

思考：  
尝试各种索引  提示：ts['2016'] 有效吗？

## 时间戳数据与周期索引的转换

In [29]:
# 时间戳数据可以转换为具有to_period的周期索引，反之亦然
ts = pd.Series(range(10),pd.date_range('07-10-16 8:00',periods = 10,freq = 'H'))
ts

2016-07-10 08:00:00    0
2016-07-10 09:00:00    1
2016-07-10 10:00:00    2
2016-07-10 11:00:00    3
2016-07-10 12:00:00    4
2016-07-10 13:00:00    5
2016-07-10 14:00:00    6
2016-07-10 15:00:00    7
2016-07-10 16:00:00    8
2016-07-10 17:00:00    9
Freq: H, dtype: int64

In [30]:
ts_period = ts.to_period()
ts_period

2016-07-10 08:00    0
2016-07-10 09:00    1
2016-07-10 10:00    2
2016-07-10 11:00    3
2016-07-10 12:00    4
2016-07-10 13:00    5
2016-07-10 14:00    6
2016-07-10 15:00    7
2016-07-10 16:00    8
2016-07-10 17:00    9
Freq: H, dtype: int64

# 五、数据切片

In [31]:
#使用时间段对时间序列数据进行切片操作
ts_period['2016-07-10 08:30':'2016-07-10 11:45']

2016-07-10 08:00    0
2016-07-10 09:00    1
2016-07-10 10:00    2
2016-07-10 11:00    3
Freq: H, dtype: int64

In [32]:
#使用时间戳对时间序列数据进行切片操作
ts['2016-07-10 08:30':'2016-07-10 11:45']

2016-07-10 09:00:00    1
2016-07-10 10:00:00    2
2016-07-10 11:00:00    3
Freq: H, dtype: int64

# 六、时区处理

In [33]:
#不设置时区
rng = pd.date_range('3/6/2012 00:00',periods = 15,freq = 'D')
rng.tz

In [34]:
#设置时区
rng_tz = pd.date_range('3/6/2012 00:00', periods = 15, freq = 'D', tz = 'Europe/London')
rng_tz.tz

In [35]:
#使用pytz库来获取通用时区和所有时区的信息
from pytz import common_timezones, all_timezones
print(len(common_timezones))
print(len(all_timezones))
print(set(all_timezones) - set(common_timezones))

440
592
{'Etc/UTC', 'America/Catamarca', 'Asia/Rangoon', 'Asia/Chongqing', 'Europe/Belfast', 'Pacific/Yap', 'MST7MDT', 'Asia/Thimbu', 'Etc/GMT-10', 'CST6CDT', 'Japan', 'Australia/NSW', 'Etc/GMT+3', 'Mexico/BajaNorte', 'Etc/GMT+10', 'Iran', 'America/Santa_Isabel', 'Australia/North', 'EST5EDT', 'Navajo', 'Asia/Macao', 'Asia/Ulan_Bator', 'Australia/West', 'MST', 'Etc/GMT+8', 'WET', 'America/Mendoza', 'America/Coral_Harbour', 'Egypt', 'Brazil/DeNoronha', 'Asia/Kashgar', 'EST', 'Etc/GMT-1', 'Singapore', 'Etc/GMT-6', 'US/East-Indiana', 'America/Rosario', 'Etc/GMT+1', 'America/Atka', 'Chile/Continental', 'Etc/GMT-4', 'GMT+0', 'Poland', 'Etc/GMT+0', 'GB', 'US/Aleutian', 'Universal', 'Australia/South', 'Atlantic/Faeroe', 'Etc/Zulu', 'Brazil/West', 'GB-Eire', 'Etc/GMT+6', 'Australia/Queensland', 'America/Virgin', 'Pacific/Samoa', 'US/Samoa', 'America/Buenos_Aires', 'America/Montreal', 'Iceland', 'Asia/Chungking', 'Australia/LHI', 'GMT-0', 'America/Fort_Wayne', 'Etc/Universal', 'Mexico/General', 'Etc/GMT+5', 'Etc/GMT+4', 'PST8PDT', 'America/Knox_IN', 'Asia/Katmandu', 'Asia/Saigon', 'Asia/Ujung_Pandang', 'Australia/ACT', 'Etc/GMT-12', 'NZ-CHAT', 'Mexico/BajaSur', 'Pacific/Truk', 'Brazil/Acre', 'Zulu', 'UCT', 'Hongkong', 'US/Indiana-Starke', 'Asia/Calcutta', 'Israel', 'CET', 'Turkey', 'Atlantic/Jan_Mayen', 'Europe/Tiraspol', 'EET', 'America/Shiprock', 'Etc/Greenwich', 'Asia/Ashkhabad', 'Portugal', 'Jamaica', 'Asia/Istanbul', 'Eire', 'Etc/GMT0', 'Canada/Yukon', 'PRC', 'Etc/GMT-0', 'Etc/GMT-11', 'ROK', 'Etc/GMT-13', 'Etc/GMT+7', 'Asia/Dacca', 'Asia/Harbin', 'Etc/GMT+9', 'America/Indianapolis', 'Etc/GMT-14', 'America/Cordoba', 'America/Jujuy', 'Africa/Asmera', 'Europe/Nicosia', 'Etc/GMT-7', 'Canada/Saskatchewan', 'America/Argentina/ComodRivadavia', 'Etc/GMT', 'Etc/GMT+12', 'Australia/Tasmania', 'Australia/Canberra', 'ROC', 'Kwajalein', 'Etc/UCT', 'Asia/Tel_Aviv', 'Brazil/East', 'Greenwich', 'Pacific/Johnston', 'Africa/Timbuktu', 'Australia/Yancowinna', 'Pacific/Ponape', 'America/Porto_Acre', 'Etc/GMT-9', 'Etc/GMT+11', 'Etc/GMT-2', 'America/Ensenada', 'Australia/Victoria', 'Etc/GMT-3', 'HST', 'Etc/GMT-5', 'Etc/GMT-8', 'Chile/EasterIsland', 'US/Michigan', 'America/Louisville', 'Etc/GMT+2', 'MET', 'Libya', 'W-SU', 'Cuba', 'GMT0', 'NZ', 'Antarctica/South_Pole'}

In [36]:
#创建不带时区信息的时间戳
t_naive = pd.Timestamp('2016-07-10 08:50')
t_naive

Timestamp('2016-07-10 08:50:00')

In [37]:
#将本地时间转换为具有特定时区信息的时间
t = t_naive.tz_localize(tz = 'US/Central')
t

Timestamp('2016-07-10 08:50:00-0500', tz='US/Central')

In [38]:
#将已经具有时区信息的对象转换为另一个时区
t.tz_convert('Asia/Tokyo')

Timestamp('2016-07-10 22:50:00+0900', tz='Asia/Tokyo')

In [39]:
#如何处理夏令时？
#创建带有美国中部时区的日期时间索引，并将其用作一个时间序列的索引
rng = pd.date_range('2016-03-10', periods=10, tz='US/Central')
ts = pd.Series(range(10), index=rng)
ts

2016-03-10 00:00:00-06:00    0
2016-03-11 00:00:00-06:00    1
2016-03-12 00:00:00-06:00    2
2016-03-13 00:00:00-06:00    3
2016-03-14 00:00:00-05:00    4
2016-03-15 00:00:00-05:00    5
2016-03-16 00:00:00-05:00    6
2016-03-17 00:00:00-05:00    7
2016-03-18 00:00:00-05:00    8
2016-03-19 00:00:00-05:00    9
Freq: D, dtype: int64

In [40]:
#创建带有协调世界时时区的日期时间索引，并将其用作一个时间序列的索引
rng = pd.date_range('2016-03-10', periods=10, tz='utc')
ts = pd.Series(range(10), index=rng)
ts

2016-03-10 00:00:00+00:00    0
2016-03-11 00:00:00+00:00    1
2016-03-12 00:00:00+00:00    2
2016-03-13 00:00:00+00:00    3
2016-03-14 00:00:00+00:00    4
2016-03-15 00:00:00+00:00    5
2016-03-16 00:00:00+00:00    6
2016-03-17 00:00:00+00:00    7
2016-03-18 00:00:00+00:00    8
2016-03-19 00:00:00+00:00    9
Freq: D, dtype: int64

In [41]:
#将时间序列中的时间点转换为特定的时区，以便在特定时区进行处理和分析。
ts.tz_convert('US/Central')

2016-03-09 18:00:00-06:00    0
2016-03-10 18:00:00-06:00    1
2016-03-11 18:00:00-06:00    2
2016-03-12 18:00:00-06:00    3
2016-03-13 19:00:00-05:00    4
2016-03-14 19:00:00-05:00    5
2016-03-15 19:00:00-05:00    6
2016-03-16 19:00:00-05:00    7
2016-03-17 19:00:00-05:00    8
2016-03-18 19:00:00-05:00    9
Freq: D, dtype: int64

In [42]:
#创建包含12个时间点的日期时间索引，每个时间点相隔1小时，且带有美国东部时区的信息
pd.date_range('03-12-2016 22:00', periods = 12, freq = 'H', tz = 'US/Eastern')

DatetimeIndex(['2016-03-12 22:00:00-05:00', '2016-03-12 23:00:00-05:00',
               '2016-03-13 00:00:00-05:00', '2016-03-13 01:00:00-05:00',
               '2016-03-13 03:00:00-04:00', '2016-03-13 04:00:00-04:00',
               '2016-03-13 05:00:00-04:00', '2016-03-13 06:00:00-04:00',
               '2016-03-13 07:00:00-04:00', '2016-03-13 08:00:00-04:00',
               '2016-03-13 09:00:00-04:00', '2016-03-13 10:00:00-04:00'],
              dtype='datetime64[ns, US/Eastern]', freq='H')

# 七、读取数据并制作数据框

In [43]:
#读取数据
data = pd.read_fwf("climate.txt", parse_dates = [[0, 1]], infer_datetime_format = True, header = None,)

In [44]:
#显示前几行数据
data.head()

         0_1       2
0 1950-01-01 -0.0603
1 1950-02-01  0.6268
2 1950-03-01 -0.0081
3 1950-04-01  0.5551
4 1950-05-01  0.0716

In [45]:
data.columns = ['month','value'] #修改列名
data.index = data.month #将 'month' 列的值作为新的索引，替代原来的默认整数索引
data = data.drop('month',1) #删除原始的 'month' 列，避免出现重复列

In [46]:
#显示前几行数据
data.head()

             value
month
1950-01-01 -0.0603
1950-02-01  0.6268
1950-03-01 -0.0081
1950-04-01  0.5551
1950-05-01  0.0716

In [47]:
#进行切片操作，选择索引值在 '1950' 到 '1952' 之间的所有行
#注意日期范围
data['1950':'1952']

             value
month
1950-01-01 -0.0603
1950-02-01  0.6268
1950-03-01 -0.0081
1950-04-01  0.5551
1950-05-01  0.0716
1950-06-01  0.5386
1950-07-01 -0.8025
1950-08-01 -0.8510
1950-09-01  0.3580
1950-10-01 -0.3789
1950-11-01 -0.5151
1950-12-01 -1.9281
1951-01-01 -0.0850
1951-02-01 -0.3999
1951-03-01 -1.9341
1951-04-01 -0.7765
1951-05-01 -0.8628
1951-06-01 -0.9179
1951-07-01  0.0900
1951-08-01 -0.3774
1951-09-01 -0.8178
1951-10-01 -0.2129
1951-11-01 -0.0685
1951-12-01  1.9872
1952-01-01  0.3682
1952-02-01 -1.7472
1952-03-01 -1.8595
1952-04-01  0.5385
1952-05-01 -0.7735
1952-06-01 -0.4409
1952-07-01  0.3831
1952-08-01 -0.0304
1952-09-01 -0.3834
1952-10-01 -0.4372
1952-11-01 -1.8909
1952-12-01 -1.8267

In [48]:
#索引类型
type(data.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [49]:
#进行切片操作，选择索引值在 '1951-11-11' 到 '1951-11-12' 之间的所有行
data['1951-11-11':'1951-11-12']

Empty DataFrame
Columns: [value]
Index: []

In [50]:
#获取周期索引
data_pd = data.to_period()

In [51]:
#切片
data_pd['1951-11-11':'1951-11-12']

          value
month
1951-11 -0.0685

In [52]:
#切片
data_pd['1951-11-11':'1952-01-12']

          value
month
1951-11 -0.0685
1951-12  1.9872
1952-01  0.3682

In [53]:
#各种数据加载是如何执行的？
#测试 Pandas 的 read_fwf() 函数在不同参数配置下的性能
import timeit

print("infer_datetime_format = True, no date parser")
%timeit pd.read_fwf("climate.txt", parse_dates = [[0, 1]], infer_datetime_format = True, header = None,)

print("infer_datetime_format = False, no date parser")
%timeit pd.read_fwf("climate.txt", parse_dates = [[0, 1]], infer_datetime_format = False, header = None,)

print("infer_datetime_format = True, date parser provided")
dateparse = lambda x, y: pd.datetime.strptime('%s-%s'%(x,y), '%Y-%m')
%timeit pd.read_fwf("climate.txt", parse_dates = [[0, 1]], infer_datetime_format = True, date_parser = dateparse,  header = None,)

print("infer_datetime_format = False, date parser provided")
dateparse = lambda x, y: pd.datetime.strptime('%s-%s'%(x,y), '%Y-%m')
%timeit pd.read_fwf("climate.txt", parse_dates = [[0, 1]], infer_datetime_format = False, date_parser = dateparse,  header = None,)

infer_datetime_format = True, no date parser
10 ms ± 92.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
infer_datetime_format = False, no date parser
9.69 ms ± 64.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
infer_datetime_format = True, date parser provided
19.1 ms ± 97.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
infer_datetime_format = False, date parser provided
19.2 ms ± 125 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [54]:
# 在已经有了数据框的情况下解析列
df = pd.DataFrame({'year': [2015, 2016],'month': [2, 3],'day': [4, 5],'hour': [2, 3]})
df

   year  month  day  hour
0  2015      2    4     2
1  2016      3    5     3

In [55]:
#将包含日期时间信息的数据转换为 Pandas 中的 datetime 类型
pd.to_datetime(df)

0   2015-02-04 02:00:00
1   2016-03-05 03:00:00
dtype: datetime64[ns]

In [56]:
#将 'year'、'month' 和 'day' 列的数据合并成一个日期时间列，并将结果转换为 Pandas 中的 datetime 类型
pd.to_datetime(df[['year', 'month', 'day']])

0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

思考：  
1.  是否适用于其他列名  
2.  去获取你自己的时间序列数据并加载，能看到什么？  
3.  （1）绘制图表   （2）获取时间范围    （3）在时间序列分析中，在时间戳和时间段之间进行转换。

In [57]:
#创建时间序列，并对该时间序列进行了截取操作
ts = pd.Series(range(10), index = pd.date_range('7/31/2015', freq = 'M', periods = 10))
ts.truncate(before='10/31/2015', after='12/31/2015')

2015-10-31    3
2015-11-30    4
2015-12-31    5
Freq: M, dtype: int64

In [58]:
#在截断时间序列时，可能会破坏时间序列的频率。需要谨慎选择截断方式，确保截断后的时间序列仍然保持为需要的频率。
#返回索引为 0、2 和 6 的数据点对应的时间索引
ts[[0, 2, 6]].index

DatetimeIndex(['2015-07-31', '2015-09-30', '2016-01-31'], dtype='datetime64[ns]', freq=None)

In [59]:
#对时间序列 ts 进行按位置的切片操作
ts.iloc[0:10:2].index

DatetimeIndex(['2015-07-31', '2015-09-30', '2015-11-30', '2016-01-31',
               '2016-03-31'],
              dtype='datetime64[ns]', freq='2M')

**总结**  
在本关卡中，我们详细介绍了Pandas在时间数据处理方面的多种功能和应用。通过一系列的示例和练习，我们学习了如何创建和操作时间戳（Timestamp）、日期时间索引（DatetimeIndex）、时间段（Period）、时间差（Timedelta）以及周期索引（PeriodIndex）。此外，我们还探讨了时区处理、节假日日历的创建和数据加载的技巧。

In [60]:
import pandas as pd
import numpy as np

# Step1：完成闯关题

## Q1  TimeStamp的使用  
将2024年8月13日16点59分这个时间转换为pandas的timestamp，将结果赋值给a1，并运行

In [26]:
a1 = pd.Timestamp("2024-08-13 16:59")

## Q2  DatetimeIndex的使用  
获取Q1时间戳的下一个周一是什么时间，将结果赋值给a2，并运行

In [28]:
a2 = a1 + pd.offsets.Week(weekday=0)

<h2>Q3 Timedelta的使用</h2><p>给Q1时间戳加上1分钟，把结果赋值给a3，并运行</p>

In [32]:
a3 = a1 + pd.Timedelta("1m")

## Q4 PeriodIndex的使用  
给定一个ts变量，使用切片获得在 2024-08-13 11:00:00 到 2024-08-13 11:30:00 的数据对应的值，将结果取第一个元素（即**索引为0**）赋值给a4，并运行

In [39]:
import pandas as pd

# 1. 创建时间序列
ts = pd.Series(range(10), pd.date_range('08-13-24 8:00', periods=10, freq='37min'))
print("ts完整数据：\n", ts)

# 2. 显式定义起止时间
start = pd.Timestamp("2024-08-13 11:00:00")
end = pd.Timestamp("2024-08-13 11:30:00")

# 3. 切片+取首元素
slice_ts = ts[start:end]
print("\n切片后的数据：\n", slice_ts)

a4 = slice_ts.iloc[0]
print("\na4的值：", a4)

ts完整数据：
 2024-08-13 08:00:00    0
2024-08-13 08:37:00    1
2024-08-13 09:14:00    2
2024-08-13 09:51:00    3
2024-08-13 10:28:00    4
2024-08-13 11:05:00    5
2024-08-13 11:42:00    6
2024-08-13 12:19:00    7
2024-08-13 12:56:00    8
2024-08-13 13:33:00    9
Freq: 37T, dtype: int64

切片后的数据：
 2024-08-13 11:05:00    5
Freq: 37T, dtype: int64

a4的值： 5

## Q5 时区处理  
通过学习教案得到**上海东八区时间**的时区表示（用时区偏移量表示），将该字符串赋值给a5，并运行(参考教案pytz库来获取通用时区）  
提示：表示时区偏移量的的格式为 Etc/GMT±X

In [40]:
a5 = 'Etc/GMT-8' #如a5='Etc/GMT-4'

# STEP2：将结果保存为 csv 文件  
csv 需要有两列，列名：id、answer。其中，id 列为题号，如 q1、q2；answer 列为 STEP1 中各题你计算出来的结果。  
💡 这一步的代码你不用做任何修改，直接运行即可。

In [41]:
# 生成 csv 作业答案文件
def save_csv(a1,a2,a3,a4,a5):
    import pandas as pd
    df = pd.DataFrame({"id": ["q1","q2","q3","q4","q5"], "answer": [a1,a2,a3,a4,a5]})
    df.to_csv("answer_1.csv", index=None)

save_csv(a1,a2,a3,a4,a5)  # 运行这个cell,生成答案文件；该文件在左侧文件树project工作区下，你可以自行右击下载或者读取查看

# STEP3: 提交 csv 文件，获取分数结果  
你的 csv 答案文件已经准备完毕了，最后让我们提交答案文件，看看是否正确。  
提交方法：  
1、拷贝提交 token  
去对应关卡的 [提交页面](https://www.heywhale.com/home/competition/66d570466e0e8469ab667015/submit)，找到对应关卡，看到了你的 token 嘛？  
拷贝它。  
记得：每个关卡的 token 不一样。  
2、下方 cell 里，拿你拷贝的 token 替换掉 XXXXXXX， 然后 Ctrl+Enter 运行

In [42]:
#运行这个Cell 下载提交工具

!wget -nv -O heywhale_submit https://cdn.kesci.com/submit_tool/v4/heywhale_submit&&chmod +x heywhale_submit

# 运行提交工具
# 把下方XXXXXXX替换为你的 Token
# 改完看起来像是：!./heywhale_submit -token 586eeef71cb92941 -file answer_1.csv

!./heywhale_submit -token 7fefe02e94b05e63 -file answer_1.csv  # 替换XXXXXXX；注意不可增减任何空格或其他字符

wget: /opt/conda/lib/libcrypto.so.1.0.0: no version information available (required by wget)
wget: /opt/conda/lib/libssl.so.1.0.0: no version information available (required by wget)
wget: /opt/conda/lib/libssl.so.1.0.0: no version information available (required by wget)
2026-03-30 07:20:16 URL:https://cdn.kesci.com/submit_tool/v4/heywhale_submit [22020102/22020102] -> "heywhale_submit" [1]
Heywhale Submit Tool: v5.0.1
> 已验证Token
> 开始上传文件
97 / 97 [||||||||||||||||||||||||||||||||||||||||||||||||||||||||] ? p/s 100.00%
> 文件已上传
> 服务器响应: 200 提交成功，请等待评审完成
> 提交完成